services:
  database:
    env_file: "../.env"
    image: postgres
    restart: always
    shm_size: 2gb
    volumes:
      - ../sql/tables.sql:/docker-entrypoint-initdb.d/init.sql
  shop:
    env_file: "../.env"
    build:
      context:    ../
      dockerfile: ./deploy/Dockerfile
    restart: always

    ports:
      - "8080:8080"