services:
  test_database:
    env_file: "./.env"
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ../../sql/tables.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  test_shop:
    depends_on:
      test_database:
        condition: service_healthy
    links:
      - test_database
    env_file: "./.env"
    build:
      context:    ../../
      dockerfile: ./e2e/resources/Dockerfile
    restart: always

    ports:
      - "8080:8080"
    networks:
      - internal
networks:
  internal: